[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/docker-compose.yml"

[deploy]
startCommand = "cd docker && unset PGPORT && docker compose up -d"
restartPolicyType = "ON_FAILURE"

[[deploy.volumes]]
path = "/var/lib/postgresql/data"
size = "5"
