[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "unset PGPORT; docker-entrypoint.sh postgres --port=5432"
restartPolicyType = "ON_FAILURE"

[[deploy.volumes]]
path = "/var/lib/postgresql/data"
size = "5"
